version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  django:
    build: .
    container_name: django_admin
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  bot:
    build: .
    container_name: bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "manage.py", "runbot"]

volumes:
  postgres_data: