# Generated by Django 5.1.7 on 2025-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
